services:
  mysql:
    image: mysql:8.4
    container_name: biblioteca-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: biblioteca_user
      MYSQL_PASSWORD: root1234
      MYSQL_ROOT_PASSWORD: biblioteca123
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
